site_name: Tendourisu's Site
site_author: Tendourisu
site_url: https://tendourisu.github.io
site_description: Tendourisu 的个人网站
repo_url: https://github.com/Tendourisu/tendourisu.github.io/
repo_name: Tendourisu's Site
copyright: Copyright &copy; 2024 - Present <a href="https://github.com/Tendourisu/" target="_blank" rel="noopener">Tendourisu</a>

theme:
  name: material
  language: en
  custom_dir: overrides

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: light mode # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: dark mode

  font:
    text: JetBrains Mono

  favicon: img/aris.png

  icon:
    logo: material/coffee
    repo: fontawesome/brands/git-alt
    edit: material/pencil

  static_templates:
    - 404.html

plugins:
  - blogging:
      locale: en
      dirs:
        - blogs/posts
      show_total: true
      features:
        tags:
          index_page: tags/
          insert: top
  - callouts
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - index.md
        - academy.md
        - links.md
        - changelog.md
  - minify:
      minify_html: true
  - mkdocs-video:
      video_muted: True
      video_controls: True
      mark: "video"
  - rss:
      enabled: false
      use_material_social_cards: false
  - search
  - statistics:
      words_per_minute: 200

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - nl2br
  - pymdownx.arithmatex: # latex支持
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      auto_title: true # 显示编程语言名称
      linenums: true # 显示行号
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  # - https://busuanzi.icodeq.com/busuanzi.pure.mini.js
  - js/mathjax.js
  - js/toc.js

extra_css:
  - css/custom.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/fold_toc.css
  - css/card.css
  - css/flink.css
  - css/tasklist.css

extra:
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/Tendourisu/
      name: GitHub
    - icon: /fontawesome/brands/qq
      link: /img/qq.jpg
      name: 加加我的QQ
    - icon: /fontawesome/brands/weixin
      link: /img/wechat.jpg
      name: 加加我的微信
    - icon: /fontawesome/brands/x-twitter
      link: https://x.com/tendourisu
      name: X
    - icon: /fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/tendourisu
      name: Zhihu
    - icon: fontawesome/solid/paper-plane
      link: mailto:2681708668@qq.com
      name: send email to me!
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_created.xml
    #   name: RSS created
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_updated.xml
    #   name: RSS updatedfeed_rss_created.xml

  # analytics:
  #   provider: google
  #   property: G-20LWGZNLLR
  #   feedback:
  #     title: Support Me!
  #     ratings:
  #       - icon: fontawesome/regular/hand-back-fist
  #         name: Support Me!
  #         data: 1
  #         note: >-
  #           <center> 难道说……你愿意给我买一瓶快乐水吗！🫣 </center>
  #           <center> How about...buy me a coffee？😋 </center>
  #           <img src="https://cdn.jsdelivr.net/gh/KinnariyaMamaTanha/Images@images/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_2024-12-07_230055_143.png" width=200px>

nav:
  - Home: index.md
  - Notes:
      - index: notes/index.md
      - CS61C:
          - "lec01-Intro": notes/cs61c/lec01-Intro.md
          - "lec02-C基础1": notes/cs61c/lec02-C基础1.md
          - "lec03-C基础2": notes/cs61c/lec03-C基础2.md
          - "lec04-C基础3": notes/cs61c/lec04-C基础3.md
          - "lec05-C浮点数基础": notes/cs61c/lec05-C浮点数基础.md
          - "lec06-RISCV指令基础1": notes/cs61c/lec06-RISCV指令基础1.md
          - "lec07-RISCV指令基础2": notes/cs61c/lec07-RISCV指令基础2.md
          - "lec08-RISCV指令总结": notes/cs61c/lec08-RISCV指令总结.md
          - "lec09-lec09-RISC-V汇编-编译-链接流程总结": notes/cs61c/lec09-RISC-V汇编-编译-链接流程总结.md
          - "lec10-数字电路基础": notes/cs61c/lec10-数字电路基础.md
          - "lec11-时序电路&模拟电路基础": notes/cs61c/lec11-时序电路&模拟电路基础.md
          - "lec12-RISC-V处理器设计": notes/cs61c/lec12-RISC-V处理器设计.md
          - "lec13-RISC-V的控制器实现与流水线入门": notes/cs61c/lec13-RISC-V的控制器实现与流水线入门.md
          - "lec14-RISC-V 流水线与处理器": notes/cs61c/lec14-RISC-V 流水线与处理器.md
          - "lec15-缓存系统": notes/cs61c/lec15-缓存系统.md
          - "lec16-缓存系统总结": notes/cs61c/lec16-缓存系统总结.md
          - "lec17-缓存总结": notes/cs61c/lec17-缓存总结.md
          - "riscv代码习惯": notes/cs61c/riscv代码习惯.md
      - easy-rl:
          - "easy-rl-chapter1-强化学习基础": notes/easy-rl/easy-rl-chapter1-强化学习基础.md
          - "easy-rl-chapter2-马尔科夫决策过程MDP": notes/easy-rl/easy-rl-chapter2-马尔科夫决策过程MDP.md
          - "easy-rl-chapter3-表格型方法": notes/easy-rl/easy-rl-chapter3-表格型方法.md
          - "easy-rl-chapter4-策略梯度": notes/easy-rl/easy-rl-chapter4-策略梯度.md
          - "easy-rl-chapter5-近端策略优化PPO": notes/easy-rl/easy-rl-chapter5-近端策略优化PPO.md
          - "easy-rl-chapter6-DQN": notes/easy-rl/easy-rl-chapter6-DQN.md
          - "easy-rl-chapter7-DQN进阶技巧": notes/easy-rl/easy-rl-chapter7-DQN进阶技巧.md
          - "easy-rl-chapter8-针对连续动作的深度Q网络": notes/easy-rl/easy-rl-chapter8-针对连续动作的深度Q网络.md
          - "easy-rl-chapter9-演员-评论员算法总结": notes/easy-rl/easy-rl-chapter9-演员-评论员算法总结.md
          - "POMDP的一些参数说明": notes/easy-rl/POMDP的一些参数说明.md
          - "RL入门汇总": notes/easy-rl/RL入门汇总.md
          - "RLfromDeepSeek": notes/easy-rl/RLfromDeepSeek.md
          - "王树森Reinforcement_Learning学习笔记": notes/easy-rl/王树森Reinforcement_Learning学习笔记.md
      - CS231N:
          - "cs231n": notes/cs231n/cs231n.md
  # - Summaries:
  #     - index: summary/index.md
  #     - "2025":
  #         - "2025-W08-02": summary/2025/2025-W08-02.md
  #         - "2025-W09-02": summary/2025/2025-W09-02.md
  #         - "2025-W11-03": summary/2025/2025-W11-03.md
  #         - "2025-W12-03": summary/2025/2025-W12-03.md
  #         - "2025-W16-04": summary/2025/2025-W16-04.md
  - Tools:
      - Tools/index.md
      - Cheat Sheet:
          - Tools/Cheat Sheet/Cheat Sheet.md
          - Tools/Cheat Sheet/Tools 待整理.md
          - Tools/Cheat Sheet/常用命令.md
          - Tools/Cheat Sheet/常用配置文件.md
          - tools:
              - Tools/Cheat Sheet/tools/adb Cheat Sheet.md
              - Tools/Cheat Sheet/tools/bash Cheat Sheet.md
              - Tools/Cheat Sheet/tools/ffmpeg Cheat Sheet.md
              - Tools/Cheat Sheet/tools/gdb Cheat Sheet.md
              - Tools/Cheat Sheet/tools/git Cheat Sheet.md
              - Tools/Cheat Sheet/tools/ip Cheat Sheet.md
              - Tools/Cheat Sheet/tools/tmux Cheat Sheet.md
              - Tools/Cheat Sheet/tools/Docker Cheat Sheet.md
              - Tools/Cheat Sheet/tools/KDE Cheat Sheet.md
              - Tools/Cheat Sheet/tools/Makeflie Cheat Sheet.md
              - Tools/Cheat Sheet/tools/chezmoi Cheat Sheet.md
              - Tools/Cheat Sheet/tools/mkdocs Cheat Sheet.md
              - Tools/Cheat Sheet/tools/network Cheat Sheet.md
              - Tools/Cheat Sheet/tools/ssh Cheat Sheet.md
              - Tools/Cheat Sheet/tools/tabby Cheat Sheet.md
              - Tools/Cheat Sheet/tools/wandb Cheat Sheet.md
              - Tools/Cheat Sheet/tools/zotero Cheat Sheet.md
              - Tools/Cheat Sheet/tools/小鹤双拼 Cheat Sheet.md
              - Tools/Cheat Sheet/tools/远程连接 Cheat Sheet.md
          - editors:
              - Tools/Cheat Sheet/editors/emacs Cheat Sheet.md
              - Tools/Cheat Sheet/editors/nano Cheat Sheet.md
              - Tools/Cheat Sheet/editors/VScode Cheat Sheet.md
              - Tools/Cheat Sheet/editors/org Cheat Sheet.md
              - Tools/Cheat Sheet/editors/vim Cheat Sheet.md
              - Tools/Cheat Sheet/editors/nvim Cheat Sheet.md
              - Tools/Cheat Sheet/editors/cursor Cheat Sheet.md
          - languages:
              - Tools/Cheat Sheet/languages/javascript Cheat Sheet.md
              - Tools/Cheat Sheet/languages/python Cheat Sheet.md
              - Tools/Cheat Sheet/languages/vimscript Cheat Sheet.md
              - Tools/Cheat Sheet/languages/Go Cheat Sheet.md
              - Tools/Cheat Sheet/languages/markdown Cheat Sheet.md
              - Tools/Cheat Sheet/languages/typst Cheat Sheet.md
          - System:
              - Tools/Cheat Sheet/System/Arch Cheat Sheet.md
      - AI:
          - Tools/AI/prompt.md
          - Tools/AI/prompt_writing.md
      - Blog:
          - Tools/Blog/Mkdocs_Material.md
      - Environment:
          - Tools/Environment/Arch_setup.md
          - Tools/Environment/Ubuntu_setup.md
          - Tools/Environment/environment.md
          - Tools/Environment/obsidian_setup.md
      - Make:
          - Tools/Make/CMake.md
          - Tools/Make/Makeflie.md   
      - Others:
          - Tools/Others/Chezmoi.md
          - Tools/Others/SSH.md
          - Tools/Others/zotero_使用指南.md
      - Terminal:
          - Tools/Terminal/Tabby_Zsh.md
  - Blogs:
    - index: blogs/index.md
  - Tags: tags/index.md
  - Links: links/index.md
  - About: about/index.md
